#!/usr/bin/env node
import * as esbuild from "esbuild";
import { cpSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { resolveBuildDefaults } from "./resolve-default-api-url.mjs";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(pkgRoot, "../..");
const outDir = join(pkgRoot, "dist");
const iconSource = join(repoRoot, "src/app/icon.png");
const ICON_SIZES = [16, 32, 48, 128];

mkdirSync(outDir, { recursive: true });

const buildDefaults = resolveBuildDefaults();
const builtinApiUrl = buildDefaults.apiUrl ?? "";
const builtinConfigured = buildDefaults.serverConfigured;

function writeGeneratedDefaults() {
  const generatedTs = `/** Generated by scripts/build.js — do not edit. */
export const BUILTIN_API_URL = ${JSON.stringify(builtinApiUrl)};
export const BUILTIN_SERVER_CONFIGURED = ${builtinConfigured};
`;

  const generatedPopup = `// Generated by scripts/build.js — do not edit.
window.__DOTVAULT_DEFAULTS__ = {
  apiUrl: ${JSON.stringify(builtinApiUrl)},
  serverConfigured: ${builtinConfigured},
};
`;

  writeFileSync(join(pkgRoot, "src/generated/defaults.ts"), generatedTs);
  writeFileSync(join(pkgRoot, "popup/defaults.generated.js"), generatedPopup);
}

const buildOptions = {
  bundle: true,
  target: "chrome120",
  format: "iife",
  logLevel: "info",
};

async function build() {
  writeGeneratedDefaults();

  await esbuild.build({
    ...buildOptions,
    entryPoints: [join(pkgRoot, "src/background.ts")],
    outfile: join(outDir, "background.js"),
  });

  await esbuild.build({
    ...buildOptions,
    entryPoints: [join(pkgRoot, "src/content.ts")],
    outfile: join(outDir, "content.js"),
  });

  cpSync(join(pkgRoot, "manifest.json"), join(outDir, "manifest.json"));
  cpSync(join(pkgRoot, "popup/popup.html"), join(outDir, "popup.html"));
  cpSync(join(pkgRoot, "popup/popup.js"), join(outDir, "popup.js"));
  cpSync(join(pkgRoot, "popup/popup.css"), join(outDir, "popup.css"));
  cpSync(
    join(pkgRoot, "popup/defaults.generated.js"),
    join(outDir, "defaults.js"),
  );
  cpSync(join(pkgRoot, "content/content.css"), join(outDir, "content.css"));

  await buildIcons();

  if (builtinApiUrl) {
    console.log(`Extension default API URL: ${builtinApiUrl}`);
  } else {
    console.log(
      "Extension default API URL: (none — user must set server URL in popup)",
    );
  }
}

async function buildIcons() {
  if (!existsSync(iconSource)) {
    throw new Error(
      `Extension icon source missing at ${iconSource}. Expected src/app/icon.png in the repo root.`,
    );
  }

  const iconsOut = join(outDir, "icons");
  mkdirSync(iconsOut, { recursive: true });

  await Promise.all(
    ICON_SIZES.map(async (size) => {
      await sharp(iconSource)
        .resize(size, size)
        .png()
        .toFile(join(iconsOut, `icon${size}.png`));
    }),
  );
}

await build();
